version: "3.5"
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  selection-web:
    image: akekmitl/selection-web
    container_name: selection-web
    build:
      context: selection-web
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    restart: on-failure
    ports:
      - "3000:3000"
  campaign-service:
    image: akekmitl/campaign-service
    container_name: campaign-service
    restart: always
    environment:
      WAIT_HOSTS: eureka:8761
      EUREKA_CLIENT_HOST: 'campaign-service'
      EUREKA_CLIENT_URL: 'http://campaign-service:'
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eureka
    ports:
      - "3002:3002"
  user-service:
    image: akekmitl/user-service
    container_name: user-service
    restart: on-failure
    environment:
      WAIT_HOSTS: eureka:8761
      EUREKA_CLIENT_HOST: 'user-service'
      EUREKA_CLIENT_URL: 'http://user-service:'
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eureka
    ports:
      - "3001:3001"
  report-service:
    image: akekmitl/report-service
    container_name: report-service
    restart: on-failure
    environment:
      WAIT_HOSTS: eureka:8761
      EUREKA_CLIENT_HOST: 'report-service'
      EUREKA_CLIENT_URL: 'http://report-service:'
      EUREKA_SERVER_HOST: 'eureka'
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eureka
    ports:
      - "3003:3003"
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: on-failure
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  #   depends_on:
  #     - campaign-service
  #     - user-service
  #     - report-service
  #     - selection-web
  #     - eureka
  eureka:
    container_name: eureka
    image: springcloud/eureka
    ports:
      - '8761:8761'
