version: 2
  jobs:
    selection-web: 
    working_directory: ~/SOA2019_Group11/selection-web/
    docker:
      - image: 'circleci/node:8'
          steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: 'yarn test'
    
      