version: 2
jobs:

    user-service:
        working_directory: ~/SOA2019_Group11/user-service/
        docker:
            - image: circleci/node:11.13.0
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout:
                path: ~/SOA2019_Group11
            - run:
                name: Install module
                command: npm install
            - run:
                name: Build Docker mechanics service Image
                command: |
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                    docker build -t $DOCKER_USERNAME/user-service .
                    docker push $DOCKER_USERNAME/user-service

    campaign-service:
        working_directory: ~/SOA2019_Group11/campaigns-service/
        docker:
            - image: circleci/node:11.13.0
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout:
                path: ~/SOA2019_Group11
            - run:
                name: Install module
                command: npm install
            - run:
                name: Build Docker Customer service Image
                command: |
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                    docker build -t $DOCKER_USERNAME/campaigns-service .
                    docker push $DOCKER_USERNAME/campaigns-service

    report-service:
        working_directory: ~/SOA2019_Group11/reports-service/
        docker:
            - image: circleci/node:11.13.0
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout:
                path: ~/SOA2019_Group6
            - run:
                name: Install module
                command: npm install
            - run:
                name: Build Docker request service Image
                command: |
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                    docker build -t $DOCKER_USERNAME/report-service .
                    docker push $DOCKER_USERNAME/report-service:

    web:
        working_directory: ~/SOA2019_Group11/selection-web
        docker:
            - image: circleci/node:11.13.0
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout:
                path: ~/SOA2019_Group11
            - run:
                name: Install module
                command: npm install
            - run:
                name: Build Docker request service Image
                command: |
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                    docker build -t $DOCKER_USERNAME/selection-web .
                    docker push $DOCKER_USERNAME/selection-web

workflows:
    version: 2
    complie:
        jobs:
            - user-service:
                filters:
                    branches:
                        only:
                            - master
            - campaign-service:
                filters:
                    branches:
                        only:
                            - master
            - report-service:
                filters:
                    branches:
                        only:
                            - master
            - web:
                filters:
                    branches:
                        only:
                            - master
