version: 2
jobs:
    user-service: 
      working_directory: ~/SOA2019_Group11/user_service 
      docker:
        - image: google/cloud-sdk
      steps:
        - setup_remote_docker:
                docker_layer_caching: true
        - checkout:
            path: ~/SOA2019_Group11
        - run:
            name: To authenticate using JSON key file
            command: |
              echo $PASS > gcloud-service-key.json
              gcloud auth activate-service-account ${ACCOUNT_ID} --key-file gcloud-service-key.json
              gcloud config set project $PROJECT_ID
        - run:
            name: 'Build Project'
            command: |
              docker build -t gcr.io/$PROJECT_ID/user_service:${CIRCLE_SHA1} .
              docker push gcr.io/PROJECT_ID/user_service:${CIRCLE_SHA1}
    # server-deploy:
    #   machine:
    #     enabled: true
    #   steps:
    #     - run:
    #         name: Secure deploy
    #         command: |
    #             docker-compose up
                
workflows:
  version: 2
  deploy:
    jobs:
      - user-service
        # - service-deploy:
        #     requires:
        #       - user-service