apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
    - port: 3000
  selector:
    app: user-service
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-service
        tier: frontend
    spec:
      containers:
      - image: gcr.io/soa-project-selection-234112/user_service:1.0
        name: user-service
        ports:
        - containerPort: 3000
          name: user-service